# Test Comment
instance_count = "1"
dns_host_base = "splunk"
instance_type = "t2.small"
instance_role = "S3-Read-Only"
key_name = "EC2_Dunstan"
ami_choice = "ami-1a7f6d7e"
route53_zone_name = "dv-aws.uk."
tagbase ="TF - IPV6"
charging_tag ="TF IPV6"
region ="eu-west-2"
subnet_map_public_ip ="true"
subnet_count ="3"
vpc_cidr_block ="10.0.0.0/16"
